/**
 * GET /api/data
 *
 * Fetches up to 100 rows from the first EGDesk table.
 *
 * EGDesk key concepts shown here:
 *  - `TABLES` from egdesk.config.ts — auto-generated list of your tables
 *  - `queryTable` from egdesk-helpers.ts — runs a SELECT with optional filters/sort/limit
 *
 * Both files are generated by EGDesk automatically when you import data.
 * You should NOT edit them by hand — they are regenerated on schema changes.
 */

import { NextResponse } from 'next/server';

// These imports resolve after EGDesk setup runs (npx egdesk-next-setup).
// They are auto-generated — do not edit egdesk.config.ts or egdesk-helpers.ts directly.
// @ts-ignore — file is generated at setup time
import { TABLES } from '../../../egdesk.config';
// @ts-ignore — file is generated at setup time
import { queryTable } from '../../../egdesk-helpers';

export async function GET() {
  try {
    // TABLES is a map of your EGDesk tables.
    // Each entry has: name, displayName, columnCount, columns, rowCount
    const tableKeys = Object.keys(TABLES) as (keyof typeof TABLES)[];

    if (tableKeys.length === 0) {
      return NextResponse.json(
        { error: 'No tables found. Import data in EGDesk first, then run npx egdesk-next-setup.' },
        { status: 404 }
      );
    }

    // Use the first available table as a demo
    const firstTable = TABLES[tableKeys[0]];

    // queryTable(tableName, options) — runs a SELECT on the given table.
    // Options: limit, offset, filters, orderBy, orderDir
    const result = await queryTable(firstTable.name, { limit: 100 });

    return NextResponse.json({
      tableName: firstTable.displayName,
      columns: firstTable.columns,
      rows: result.rows ?? [],
      total: result.total ?? (result.rows?.length ?? 0),
    });
  } catch (error: any) {
    console.error('[/api/data] Error:', error);
    return NextResponse.json({ error: error.message ?? 'Internal error' }, { status: 500 });
  }
}
