/**
 * egdesk.config.ts
 *
 * ⚠️  AI ASSISTANT — READ-ONLY. DO NOT MODIFY THIS FILE.
 *
 * This file is auto-generated by EGDesk and re-generated whenever your schema changes.
 * It reflects your DEVELOPMENT tables only. Production tables are managed separately.
 *
 * To regenerate manually:
 *   npx egdesk-next-setup
 */

export const TABLES = {
  products: {
    name: 'products',
    displayName: 'Products',
    columns: ['name', 'description', 'price', 'category', 'stock'],
    columnCount: 5,
    rowCount: 0,
  },
  customers: {
    name: 'customers',
    displayName: 'Customers',
    columns: ['first_name', 'last_name', 'email', 'phone', 'created_at'],
    columnCount: 5,
    rowCount: 0,
  },
  orders: {
    name: 'orders',
    displayName: 'Orders',
    columns: ['customer_id', 'product_id', 'quantity', 'total_price', 'status', 'ordered_at'],
    columnCount: 6,
    rowCount: 0,
  },
} as const;

export type TableName = keyof typeof TABLES;
export const TABLE_NAMES = Object.keys(TABLES) as TableName[];
