/**
 * EGDesk visitor Google helpers (published-site visitors).
 *
 * Visitors become EGDesk Auth users. Login is brokered by EGDesk so this
 * site never receives SUPABASE_URL or the anon key.
 * The opaque session is bound to this site origin and will not work on
 * another published site that shares the same EGDesk.
 *
 * Import this file only from pages that need visitor Google.
 *
 * Generated by @egdesk/next-api-plugin — do not edit.
 * Customize login UI in your pages. Set default scopes in egdesk.visitor-auth.ts
 * or pass startVisitorGoogleLogin({ scopes: VISITOR_BASIC_SCOPES }).
 */

import { apiFetch } from './egdesk-helpers';
import { VISITOR_AUTH } from './egdesk.visitor-auth';

const VISITOR_SESSION_KEY = 'egdesk_visitor_session';

export type VisitorScopePreset = 'basic' | 'workspace';

export const VISITOR_BASIC_SCOPES = [
  'https://www.googleapis.com/auth/userinfo.email',
  'https://www.googleapis.com/auth/userinfo.profile',
  'openid',
] as const;

export const VISITOR_WORKSPACE_SCOPES = [
  ...VISITOR_BASIC_SCOPES,
  'https://www.googleapis.com/auth/drive.file',
  'https://www.googleapis.com/auth/spreadsheets',
  'https://www.googleapis.com/auth/documents',
  'https://www.googleapis.com/auth/presentations',
] as const;

/** @deprecated use VISITOR_WORKSPACE_SCOPES */
export const VISITOR_GOOGLE_OAUTH_SCOPES = VISITOR_WORKSPACE_SCOPES;

function resolveVisitorLoginScopes(
  override?: readonly string[] | VisitorScopePreset,
): string[] {
  if (override === 'basic') return [...VISITOR_BASIC_SCOPES];
  if (override === 'workspace') return [...VISITOR_WORKSPACE_SCOPES];
  if (Array.isArray(override) && override.length > 0) return [...override];
  const fromEnv =
    (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_VISITOR_SCOPES) || '';
  if (fromEnv === 'workspace') return [...VISITOR_WORKSPACE_SCOPES];
  if (fromEnv === 'basic') return [...VISITOR_BASIC_SCOPES];
  if (VISITOR_AUTH.scopes === 'workspace') return [...VISITOR_WORKSPACE_SCOPES];
  return [...VISITOR_BASIC_SCOPES];
}

function getVisitorSessionId(): string | null {
  if (typeof window === 'undefined') return null;
  return window.localStorage.getItem(VISITOR_SESSION_KEY);
}

function setVisitorSessionId(sessionId: string | null): void {
  if (typeof window === 'undefined') return;
  if (sessionId) window.localStorage.setItem(VISITOR_SESSION_KEY, sessionId);
  else window.localStorage.removeItem(VISITOR_SESSION_KEY);
}

async function parseEgdeskJson(response: Response): Promise<any> {
  const result = await response.json().catch(() => null);
  if (!response.ok) {
    const errMsg =
      result && typeof result === 'object' && typeof result.error === 'string'
        ? result.error
        : `Request failed (${response.status})`;
    throw new Error(errMsg);
  }
  return result;
}

function originFromValue(value?: string | null): string | null {
  const raw = (value || '').trim();
  if (!raw) return null;
  try {
    return new URL(raw).origin;
  } catch {
    try {
      return new URL(`https://${raw}`).origin;
    } catch {
      return null;
    }
  }
}

function resolveVisitorSiteOrigin(): string | null {
  if (typeof window !== 'undefined') return window.location.origin;
  const fromEnv =
    (typeof process !== 'undefined' &&
      (process.env?.NEXT_PUBLIC_EGDESK_VISITOR_ORIGIN || process.env?.NEXT_PUBLIC_SITE_URL)) ||
    '';
  return originFromValue(fromEnv);
}

function visitorOriginHeaders(): Record<string, string> {
  const origin = resolveVisitorSiteOrigin();
  if (!origin) return {};
  return { Origin: origin, 'X-Visitor-Origin': origin };
}

/** Tunnel production apps live under /t/{id}/p/{project}. Bare /auth/callback 404s. */
export function getVisitorSiteBasePath(): string {
  const fromEnv =
    (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_BASE_PATH) || '';
  if (fromEnv) return fromEnv.replace(/\/$/, '');
  if (typeof window === 'undefined') return '';
  const parts = window.location.pathname.split('/').filter(Boolean);
  if (parts[0] === 't' && parts.length >= 4 && parts[2] === 'p') {
    return `/${parts.slice(0, 4).join('/')}`;
  }
  return '';
}

export function resolveVisitorAppPath(path: string): string {
  const base = getVisitorSiteBasePath();
  const normalized = path.startsWith('/') ? path : `/${path}`;
  if (!base) return normalized;
  if (normalized === base || normalized.startsWith(`${base}/`)) return normalized;
  return `${base}${normalized}`;
}

function isLoopbackHostname(hostname: string): boolean {
  return hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '[::1]';
}

function isPrivateLanHostname(hostname: string): boolean {
  const match = hostname.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);
  if (!match) return false;
  const a = Number(match[1]);
  const b = Number(match[2]);
  if (a === 10) return true;
  if (a === 172 && b >= 16 && b <= 31) return true;
  if (a === 192 && b === 168) return true;
  return false;
}

function isDevSiteHostname(hostname: string): boolean {
  return isLoopbackHostname(hostname) || isPrivateLanHostname(hostname);
}

function isLocalEgdeskUrl(value: string): boolean {
  try {
    return isLoopbackHostname(new URL(value).hostname);
  } catch {
    return false;
  }
}

function isTunnelMcpRoot(value: string): boolean {
  try {
    const parsed = new URL(value);
    return (
      parsed.hostname === 'tunneling-service.onrender.com' ||
      parsed.hostname.endsWith('.egdesk.cloud') ||
      /\/t\/[^/]+/.test(parsed.pathname)
    );
  } catch {
    return false;
  }
}

/**
 * MCP root used as the Google/Supabase OAuth bounce.
 * Published hosts must never silently fall back to http://localhost:8080.
 */
export function resolveEgdeskPublicUrl(): string {
  const configured = (
    (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
    ''
  ).replace(/\/$/, '');
  const tunnelUrl = (
    (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_TUNNEL_URL) ||
    ''
  ).replace(/\/$/, '');
  const preferred = configured || tunnelUrl;

  if (typeof window === 'undefined') {
    return preferred || 'http://localhost:8080';
  }

  const hostname = window.location.hostname;
  const parts = window.location.pathname.split('/').filter(Boolean);
  const onTunnelPath = parts[0] === 't' && Boolean(parts[1]);
  const onKnownGateway =
    hostname === 'tunneling-service.onrender.com' || hostname.endsWith('.egdesk.cloud');

  if (onTunnelPath && (onKnownGateway || !isLoopbackHostname(hostname))) {
    return `${window.location.origin}/t/${parts[1]}`;
  }

  if (isDevSiteHostname(hostname)) {
    if (isPrivateLanHostname(hostname) && preferred && isTunnelMcpRoot(preferred)) {
      return preferred;
    }
    if (isLoopbackHostname(hostname)) {
      return preferred || 'http://localhost:8080';
    }
    if (preferred && !isLocalEgdeskUrl(preferred)) {
      return preferred;
    }
    throw new Error(
      'Visitor Google login from a LAN IP requires NEXT_PUBLIC_EGDESK_API_URL to be the tunnel MCP root (https://…/t/{id}).',
    );
  }

  if (preferred && !isLocalEgdeskUrl(preferred)) {
    return preferred;
  }

  console.error(
    '[egdesk-visitor-google] NEXT_PUBLIC_EGDESK_API_URL is missing or points at localhost on a published host. Using window.location.origin for the OAuth bounce.',
  );
  return window.location.origin;
}

async function callVisitorAuth(tool: string, args: Record<string, unknown> = {}) {
  const response = await apiFetch('/__visitor_auth_proxy', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...visitorOriginHeaders() },
    body: JSON.stringify({ tool, arguments: args }),
  });
  return parseEgdeskJson(response);
}

async function callVisitorGoogle(tool: string, args: Record<string, unknown> = {}) {
  const sessionId = getVisitorSessionId();
  if (!sessionId) {
    throw new Error('Visitor is not signed in. Call startVisitorGoogleLogin() first.');
  }
  const response = await apiFetch('/__visitor_google_proxy', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${sessionId}`,
      ...visitorOriginHeaders(),
    },
    body: JSON.stringify({ tool, arguments: args }),
  });
  return parseEgdeskJson(response);
}

/**
 * Sign a website visitor in with Google via EGDesk.
 * Creates/uses an EGDesk user; Google tokens stay under that user_id on EGDesk.
 *
 * Default scopes come from egdesk.visitor-auth.ts (never overwritten).
 * Pass scopes to override per button, e.g. VISITOR_BASIC_SCOPES or 'workspace'.
 */
export async function startVisitorGoogleLogin(options: {
  next?: string;
  forceConsent?: boolean;
  scopes?: readonly string[] | VisitorScopePreset;
} = {}) {
  if (typeof window === 'undefined') {
    throw new Error('startVisitorGoogleLogin() must run in the browser');
  }
  const next = resolveVisitorAppPath(
    options.next && options.next.startsWith('/') ? options.next : window.location.pathname,
  );
  const returnTo = new URL(resolveVisitorAppPath('/auth/callback'), window.location.origin);
  returnTo.searchParams.set('next', next);
  // Localhost → allowlisted http://localhost:54321/auth/callback.
  // Tunnel / custom domain → {MCP root}/visitor-auth/callback/{pendingId}.
  const egdeskPublicUrl = resolveEgdeskPublicUrl();
  if (isLocalEgdeskUrl(egdeskPublicUrl) && !isDevSiteHostname(window.location.hostname)) {
    throw new Error(
      'Visitor Google login cannot use a localhost EGDesk URL from a published site. Set NEXT_PUBLIC_EGDESK_API_URL to the tunnel MCP root (https://…/t/{id}).',
    );
  }
  const scopes = resolveVisitorLoginScopes(options.scopes);

  const result = await callVisitorAuth('start', {
    returnTo: returnTo.toString(),
    egdeskPublicUrl,
    forceConsent: options.forceConsent === true,
    scopes,
  });
  if (!result?.authUrl) {
    throw new Error(result?.error || 'Failed to start visitor Google login');
  }
  window.location.href = result.authUrl;
}

export async function exchangeVisitorAuthCode(code: string) {
  const result = await callVisitorAuth('exchange', { code });
  if (!result?.sessionId) {
    throw new Error(result?.error || 'Failed to complete visitor login');
  }
  setVisitorSessionId(result.sessionId);
  return result;
}

export async function signOutVisitorGoogle() {
  try {
    const sessionId = getVisitorSessionId();
    if (sessionId) {
      await callVisitorAuth('logout', { sessionId });
    }
  } finally {
    setVisitorSessionId(null);
  }
}

export async function getVisitorGoogleStatus() {
  const sessionId = getVisitorSessionId();
  if (!sessionId) {
    return { connected: false, email: null, message: 'Visitor is not signed in.' };
  }
  try {
    return await callVisitorGoogle('status');
  } catch {
    return { connected: false, email: null, message: 'Visitor is not signed in.' };
  }
}

export async function listVisitorDriveFiles(options: { pageSize?: number; query?: string } = {}) {
  return callVisitorGoogle('listDriveFiles', options);
}

export async function getVisitorSheetRange(spreadsheetId: string, range: string) {
  return callVisitorGoogle('getSheetRange', { spreadsheetId, range });
}
