'use client';

/**
 * Visitor Google OAuth callback.
 * Generated by @egdesk/next-api-plugin — PKCE verifier lives in the browser,
 * so this must be a client page (not a server route).
 *
 * Add this origin to Supabase Authentication → URL Configuration → Redirect URLs:
 *   {origin}/auth/callback
 */

import { useEffect, useState } from 'react';
import { createClient, type Session } from '@supabase/supabase-js';

const VISITOR_GOOGLE_OAUTH_SCOPES = [
  'https://www.googleapis.com/auth/userinfo.email',
  'https://www.googleapis.com/auth/userinfo.profile',
  'https://www.googleapis.com/auth/drive.file',
  'https://www.googleapis.com/auth/spreadsheets',
  'openid',
];

function getSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anonKey) {
    throw new Error(
      'Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY'
    );
  }
  return createClient(url, anonKey, {
    auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true },
  });
}

async function saveVisitorGoogleToken(session: Session) {
  const accessToken =
    (session as Session & { provider_token?: string }).provider_token || '';
  const refreshToken =
    (session as Session & { provider_refresh_token?: string }).provider_refresh_token ||
    undefined;

  if (!accessToken && !refreshToken) {
    console.warn('[visitor-google] No Google provider tokens on session — re-consent may be required');
    return;
  }

  const supabase = getSupabase();
  const { error } = await supabase.from('user_google_tokens').upsert(
    {
      user_id: session.user.id,
      provider: 'google',
      access_token: accessToken,
      refresh_token: refreshToken,
      expires_at: new Date(Date.now() + 3600 * 1000).toISOString(),
      scopes: VISITOR_GOOGLE_OAUTH_SCOPES,
      is_active: true,
      provider_email: session.user.email ?? null,
      updated_at: new Date().toISOString(),
    },
    { onConflict: 'user_id,provider' }
  );

  if (error) {
    console.error('[visitor-google] Failed to save token:', error.message);
  }
}

export default function VisitorGoogleCallbackPage() {
  const [message, setMessage] = useState('Finishing Google sign-in…');

  useEffect(() => {
    let cancelled = false;

    const run = async () => {
      try {
        const supabase = getSupabase();
        const params = new URLSearchParams(window.location.search);
        const code = params.get('code');
        const nextParam = params.get('next');
        const next = nextParam && nextParam.startsWith('/') ? nextParam : '/';

        if (code) {
          const { data, error } = await supabase.auth.exchangeCodeForSession(code);
          if (error) throw error;
          if (data.session && !cancelled) {
            await saveVisitorGoogleToken(data.session);
          }
        } else {
          const { data: { session } } = await supabase.auth.getSession();
          if (session) {
            await saveVisitorGoogleToken(session);
          }
        }

        if (!cancelled) {
          window.location.replace(next);
        }
      } catch (err) {
        const text = err instanceof Error ? err.message : String(err);
        console.error('[visitor-google] callback failed:', text);
        if (!cancelled) setMessage(text);
      }
    };

    void run();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', padding: 48, textAlign: 'center' }}>
      <p>{message}</p>
    </main>
  );
}
