/**
 * Visitor Google API — uses the visitor's own Google token (user_google_tokens).
 * Generated by @egdesk/next-api-plugin.
 *
 * Does NOT call EGDesk MCP. Owner Drive/Sheets stay on drive_auth_login.
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';

type VisitorGoogleOp = 'status' | 'listDriveFiles' | 'getSheetRange';

function jsonError(message: string, status = 400) {
  return NextResponse.json({ error: message }, { status });
}

function getSupabaseEnv() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anonKey) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY');
  }
  return { url, anonKey };
}

function createUserClient(jwt: string) {
  const { url, anonKey } = getSupabaseEnv();
  return createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${jwt}` } },
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

type TokenRow = {
  access_token: string | null;
  refresh_token: string | null;
  expires_at: string | null;
  scopes: string[] | null;
  provider_email: string | null;
};

async function loadTokenRow(jwt: string, userId: string): Promise<TokenRow | null> {
  const supabase = createUserClient(jwt);
  const { data, error } = await supabase
    .from('user_google_tokens')
    .select('access_token, refresh_token, expires_at, scopes, provider_email')
    .eq('user_id', userId)
    .eq('provider', 'google')
    .eq('is_active', true)
    .maybeSingle();

  if (error) {
    throw new Error(error.message);
  }
  return data;
}

function isExpired(expiresAt: string | null): boolean {
  if (!expiresAt) return true;
  return new Date(expiresAt).getTime() - 5 * 60 * 1000 < Date.now();
}

async function refreshViaEdgeFunction(jwt: string): Promise<{
  access_token: string;
  expires_at?: string;
} | null> {
  const { url } = getSupabaseEnv();
  const response = await fetch(`${url}/functions/v1/refresh-google-token`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${jwt}`,
      'Content-Type': 'application/json',
    },
  });
  const data = (await response.json().catch(() => null)) as {
    success?: boolean;
    access_token?: string;
    expires_at?: string;
    error?: string;
    code?: string;
  } | null;

  if (!response.ok || !data?.access_token) {
    return null;
  }
  return { access_token: data.access_token, expires_at: data.expires_at };
}

async function getVisitorGoogleAccessToken(
  jwt: string,
  userId: string
): Promise<{ token: TokenRow; accessToken: string }> {
  let row = await loadTokenRow(jwt, userId);
  if (!row || (!row.access_token && !row.refresh_token)) {
    throw new Error('No Google token for this visitor. Call startVisitorGoogleLogin() first.');
  }

  if (row.access_token && !isExpired(row.expires_at)) {
    return { token: row, accessToken: row.access_token };
  }

  const refreshed = await refreshViaEdgeFunction(jwt);
  if (refreshed?.access_token) {
    return {
      token: {
        ...row,
        access_token: refreshed.access_token,
        expires_at: refreshed.expires_at ?? row.expires_at,
      },
      accessToken: refreshed.access_token,
    };
  }

  if (row.access_token) {
    return { token: row, accessToken: row.access_token };
  }

  throw new Error('Google token expired. Sign in with Google again.');
}

export async function POST(request: NextRequest) {
  const authHeader = request.headers.get('authorization') || '';
  const jwt = authHeader.toLowerCase().startsWith('bearer ')
    ? authHeader.slice(7).trim()
    : '';

  if (!jwt) {
    return jsonError('Missing Authorization Bearer token (visitor Supabase session)', 401);
  }

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return jsonError('Invalid JSON body');
  }

  const op = body.op as VisitorGoogleOp | undefined;
  if (!op) {
    return jsonError('Missing op (status | listDriveFiles | getSheetRange)');
  }

  try {
    const supabase = createUserClient(jwt);
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) {
      return jsonError('Invalid or expired visitor session', 401);
    }

    if (op === 'status') {
      const row = await loadTokenRow(jwt, user.id);
      const expired = isExpired(row?.expires_at ?? null);
      const connected = Boolean(row?.access_token) && !expired;
      return NextResponse.json({
        connected,
        email: row?.provider_email || user.email || null,
        userId: user.id,
        expired,
        expiresAt: row?.expires_at ?? null,
        scopes: row?.scopes ?? [],
        hasRefreshToken: Boolean(row?.refresh_token),
        message: connected
          ? 'Visitor Google is connected.'
          : 'Visitor is signed in but Google Drive/Sheets is not connected. Call startVisitorGoogleLogin().',
      });
    }

    const { accessToken, token } = await getVisitorGoogleAccessToken(jwt, user.id);

    if (op === 'listDriveFiles') {
      const pageSize = Math.min(Number(body.pageSize) || 20, 100);
      const query = typeof body.query === 'string' ? body.query : '';
      const params = new URLSearchParams({
        pageSize: String(pageSize),
        fields: 'files(id,name,mimeType,modifiedTime,webViewLink)',
        q: query || "trashed = false",
      });
      const response = await fetch(
        `https://www.googleapis.com/drive/v3/files?${params.toString()}`,
        { headers: { Authorization: `Bearer ${accessToken}` } }
      );
      const data = await response.json().catch(() => ({}));
      if (!response.ok) {
        return jsonError(data?.error?.message || 'Drive list failed', response.status);
      }
      return NextResponse.json({
        files: data.files || [],
        email: token.provider_email || user.email || null,
      });
    }

    if (op === 'getSheetRange') {
      const spreadsheetId = String(body.spreadsheetId || '');
      const range = String(body.range || '');
      if (!spreadsheetId || !range) {
        return jsonError('spreadsheetId and range are required');
      }
      const response = await fetch(
        `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(spreadsheetId)}/values/${encodeURIComponent(range)}`,
        { headers: { Authorization: `Bearer ${accessToken}` } }
      );
      const data = await response.json().catch(() => ({}));
      if (!response.ok) {
        return jsonError(data?.error?.message || 'Sheets read failed', response.status);
      }
      return NextResponse.json({
        spreadsheetId,
        range: data.range || range,
        values: data.values || [],
      });
    }

    return jsonError(`Unknown op: ${op}`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return jsonError(message, 500);
  }
}
